### ISSUE TITLE
Create Github Action for Lambda Deploy

### ISSUE THREAD

**Issue by Creighcl** [dungeoneer-io/lmda-rlm-scanner#4]

**Comment by Creighcl** [comment]
- pull production code from repo
- install dependencies `npm install --only=prod`
- zip up `node_modules` `src` and `index.js`
- transmit to AWS

**Comment by Creighcl** [comment]
running tests in this pipeline will dirty the zip distro. can one action run separately and depend on result of the other?

**Comment by Creighcl** [comment]
totally:
```yml
name: Test and publish

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps: ...

  publish:
    runs-on: ubuntu-latest
    needs: test
    steps: ...

```
